import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// const ImplementationContext = React.createContext("python"); // Default to python

// // Implementation Provider component to specify which implementation to use
// export const ImplementationProvider = function (props) {
//   const implementation = props.implementation || "python";
//   const children = props.children;

//   return createElement(
//     ImplementationContext.Provider,
//     { value: implementation },
//     children,
//   );
// };

// // Export the hook to access the current atom scope
// export function useAtomScope() {
//   const implementation = React.useContext(ImplementationContext);
//
//   // Determine which implementation to use
//   if (implementation === "js") {
//     return useJSAtomScope();
//   } else {
//     // Default to Python
//     return usePythonAtomScope();
//   }
// }
//
// // Re-export common components for backward compatibility
// export { PythonEditor as CodeMirrorEditor };
// export { JSMonacoEditor as MonacoEditor };
// export { MolStar };
// export { PythonMolViewSpecApp as MolViewSpecApp };
//
// // Main application initialization function
// export function appInit(
//   container,
//   initialState,
//   initialCode,
//   mode = "python",
//   editorType = "codemirror",
// ) {
//   if (!container) return;
//
//   const root = createRoot(container);
//
//   if (mode === "python") {
//     root.render(
//       createElement(
//         ImplementationProvider,
//         { implementation: "python" },
//         createElement(
//           PythonMolViewSpecApp,
//           { initialCode: initialCode },
//           createElement(PythonEditor, { initialCode: initialCode }),
//         ),
//       ),
//     );
//   } else if (mode === "js") {
//     const Editor = editorType === "monaco" ? JSMonacoEditor : JSEditor;
//     root.render(
//       createElement(
//         ImplementationProvider,
//         { implementation: "js" },
//         createElement(
//           JSMolViewSpecApp,
//           { initialCode: initialCode },
//           createElement(Editor, { initialCode: initialCode }),
//         ),
//       ),
//     );
//   }
// }
//
// export default appInit;
