name: PR Validation

on:
  pull_request:
    branches: ["main"]
    paths:
      - "api/**"
      - ".github/workflows/pr-check.yml"

env:
  REGISTRY: cerit.io
  IMAGE_NAME: mol-view-stories/mvs-api

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd api
          pip install -r requirements.txt
          pip install flake8 black isort pytest

      - name: Run linting (flake8)
        run: |
          cd api
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run code formatting check (black)
        run: |
          cd api
          python -m black --check --diff .

      - name: Run import sorting check (isort)
        run: |
          cd api
          python -m isort --check-only --diff .

      - name: Run tests
        run: |
          cd api
          python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=html

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./api/coverage.xml
          flags: api
          name: api-coverage

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without pushing)
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: false
          load: true
          tags: mol-view-stories-api:pr-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Docker image
        run: |
          docker images mol-view-stories-api:pr-test
          docker run --rm mol-view-stories-api:pr-test python --version 

  docker-push-pr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    # Only run for PRs from this repository (secrets are not available for forks)
    if: github.event.pull_request.head.repo.fork == false
    outputs:
      image_digest: ${{ steps.build_and_push_pr.outputs.digest }}
      image_tag: pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.CERIT_REGISTRY_USERNAME }}
          password: ${{ secrets.CERIT_REGISTRY_PASSWORD }}

      - name: Build and push PR image
        id: build_and_push_pr
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}-${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-dev-pr:
    needs: docker-push-pr
    runs-on: ubuntu-latest
    # Only run for PRs from this repository (secrets are not available for forks)
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          KCONF='${{ secrets.K8S_CONTEXT }}'
          if echo "$KCONF" | base64 -d >/dev/null 2>&1; then
            echo "Detected base64-encoded kubeconfig"
            echo "$KCONF" | base64 -d > kubeconfig
          else
            echo "Using raw kubeconfig"
            printf "%s" "$KCONF" > kubeconfig
          fi
          echo "KUBECONFIG=$PWD/kubeconfig" >> "$GITHUB_ENV"

      - name: Create or update ephemeral PR deployment
        env:
          KUBECONFIG: kubeconfig
          DEPLOYMENT_NAME: mol-view-stories-pr-${{ github.event.number }}
          APP_LABEL: mol-view-stories-pr-${{ github.event.number }}
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.docker-push-pr.outputs.image_digest }}
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${DEPLOYMENT_NAME}
            namespace: mol-view-stories-ns
            labels:
              app: ${APP_LABEL}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: ${APP_LABEL}
            template:
              metadata:
                labels:
                  app: ${APP_LABEL}
              spec:
                imagePullSecrets:
                  - name: cerit-registry-secret
                containers:
                  - name: ${DEPLOYMENT_NAME}-container
                    image: ${IMAGE}
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 5000
                        name: http
                    env:
                      - name: ENVIRONMENT
                        value: "development"
                    readinessProbe:
                      httpGet:
                        path: /ready
                        port: 5000
                      initialDelaySeconds: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                      successThreshold: 1
                      failureThreshold: 3
                    securityContext:
                      runAsUser: 1000
                      runAsGroup: 1000
                      runAsNonRoot: true
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop: ["ALL"]
                      seccompProfile:
                        type: RuntimeDefault
                    resources:
                      requests:
                        memory: "256Mi"
                        cpu: "250m"
                      limits:
                        memory: "512Mi"
                        cpu: "500m"
          EOF

      - name: Set MinIO environment variables (dev)
        env:
          KUBECONFIG: kubeconfig
          DEPLOYMENT_NAME: mol-view-stories-pr-${{ github.event.number }}
        run: |
          kubectl set env deployment/${DEPLOYMENT_NAME} \
            -n mol-view-stories-ns \
            MINIO_ENDPOINT="${{ secrets.MINIO_DEV_URL }}" \
            MINIO_ACCESS_KEY="${{ secrets.MINIO_DEV_USERNAME }}" \
            MINIO_SECRET_KEY="${{ secrets.MINIO_DEV_PASSWORD }}" \
            MINIO_BUCKET="root"

      - name: Wait for rollout
        env:
          KUBECONFIG: kubeconfig
          DEPLOYMENT_NAME: mol-view-stories-pr-${{ github.event.number }}
        run: |
          kubectl rollout status deployment/${DEPLOYMENT_NAME} -n mol-view-stories-ns --timeout=300s

      - name: Verify PR deployment
        env:
          KUBECONFIG: kubeconfig
          APP_LABEL: mol-view-stories-pr-${{ github.event.number }}
        run: |
          kubectl get pods -n mol-view-stories-ns -l app=${APP_LABEL}

      - name: Cleanup PR deployment
        if: always()
        env:
          KUBECONFIG: kubeconfig
          DEPLOYMENT_NAME: mol-view-stories-pr-${{ github.event.number }}
        run: |
          kubectl delete deployment/${DEPLOYMENT_NAME} -n mol-view-stories-ns --ignore-not-found=true